plugins:
  - junit-xml-IReportType
  - xunit-xml-IReportType
  - trx-IReportType
  - behaviors-IReportType
  - packages-IReportType
  - screen-diff-IReportType
  - xctest-IReportType
  - jira-IReportType
  - xray-IReportType
